### ISSUE TITLE
Изучить контекст

### ISSUE THREAD

**Issue by Znack** [backuot/TheGameOfLife#17]
```
var _this = this;
```

такого рода костылей можно легко избежать. Обязательно изучи 4 шаблона вызова функции, и как от них зависит контекст функций. Вот статейки по этой теме, которые я в свое время сохранял:
https://habrahabr.ru/post/149516/
https://habrahabr.ru/post/149581/

**Comment by badifeg** [comment]
Мне такие конструкции из всего приложения убрать?

**Comment by Znack** [comment]
Если не подтвердишь необходимость оставить :)

**Comment by Znack** [comment]
Issue не закрыта, еще остались такие моменты. Такие проблемы можно избежать с помощью bind, а еще лучше стрелочных функций

```
  game() {
    if (!this.status) return;
    this.props.gameProcess();
    setTimeout(() => _this.game(), 700);
  }
```

Ну и еще в паре других мест есть такая же ошибка.
