### ISSUE TITLE
Логическая ошибка initialData

### ISSUE THREAD

**Issue by NikitaRzm** [backuot/TheGameOfLife#25]
В коде ниже имеются следующие ошибки:
1. Придумайте более говорящие имена для переменных n и m, мы не на низком уровне и память не экономим.
2. Зачем вам нужны аргументы n и m, если далее вы все равно их сбрасываете до дефолтных значений?

``` javascript
export function initialData(n = 33, m = 37) {
  var data = [],
      i,
      j;

  if (n > 33 || n < 0) {
    n = 33;
  }

  if (m > 37 || m < 0) {
    m = 37;
  }
```

**Comment by badifeg** [comment]
Здесь ограничения на размер матрицы 0-33 по столбцам (n) 0-37 по строкам (m). Если они не соблюдены будут присвоены значения по дефолту. В функцию можно передать другие значения nxm  - размер матрицы.

**Comment by NikitaRzm** [comment]
Тогда ваш код весьма непонятен без детального разбора даже в таких простых местах. Полагаю, данный вариант будет несколько понятнее:

``` javascript
export function initialData(n = 33, m = 37) {
  const data = [];
  let rows = inRange(n, 0, 33) ? n : 33;
  let columns = inRange(m, 0, 37) ? m : 37;
```

Функцию inRange предлагаю вам реализовать самому.

**Comment by badifeg** [comment]
Зачем здесь нужно const data = [] ?
